//
//package com.adtech.rts.service;
//
//import org.springframework.stereotype.Component;
//
//import javax.xml.namespace.QName;
//import javax.xml.ws.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//
//
///**
// * This class was generated by the JAX-WS RI.
// * JAX-WS RI 2.2.9-b130926.1035
// * Generated source version: 2.2
// */
//@Component
//@WebServiceClient(name = "YdWebServiceImplService", targetNamespace = "http://impl.yd.publish.webservice.fastwork.th.com/", wsdlLocation = "http://swap.pic.cqwsjsw.gov.cn/swap/YdWebservice?wsdl")
//public class YdWebServiceImplService
//        extends Service {
//
//    private final static URL YDWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
//    private final static WebServiceException YDWEBSERVICEIMPLSERVICE_EXCEPTION;
//    private final static QName YDWEBSERVICEIMPLSERVICE_QNAME = new QName("http://impl.yd.publish.webservice.fastwork.th.com/", "YdWebServiceImplService");
//
//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("http://swap.pic.cqwsjsw.gov.cn/swap/YdWebservice?wsdl");
//        }
//        catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//        YDWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
//        YDWEBSERVICEIMPLSERVICE_EXCEPTION = e;
//    }
//
//    public YdWebServiceImplService() {
//        super(__getWsdlLocation(), YDWEBSERVICEIMPLSERVICE_QNAME);
//    }
//
//    public YdWebServiceImplService(WebServiceFeature... features) {
//        super(__getWsdlLocation(), YDWEBSERVICEIMPLSERVICE_QNAME, features);
//    }
//
//    public YdWebServiceImplService(URL wsdlLocation) {
//        super(wsdlLocation, YDWEBSERVICEIMPLSERVICE_QNAME);
//    }
//
//    public YdWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
//        super(wsdlLocation, YDWEBSERVICEIMPLSERVICE_QNAME, features);
//    }
//
//    public YdWebServiceImplService(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public YdWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
//        super(wsdlLocation, serviceName, features);
//    }
//
//    /**
//     * @return returns YdWebServiceImpl
//     */
//    @WebEndpoint(name = "YdWebServiceImplPort")
//    public YdWebServiceImpl getYdWebServiceImplPort() {
//        return super.getPort(new QName("http://impl.yd.publish.webservice.fastwork.th.com/", "YdWebServiceImplPort"), YdWebServiceImpl.class);
//    }
//
//    /**
//     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return returns YdWebServiceImpl
//     */
//    @WebEndpoint(name = "YdWebServiceImplPort")
//    public YdWebServiceImpl getYdWebServiceImplPort(WebServiceFeature... features) {
//        return super.getPort(new QName("http://impl.yd.publish.webservice.fastwork.th.com/", "YdWebServiceImplPort"), YdWebServiceImpl.class, features);
//    }
//
//    private static URL __getWsdlLocation() {
//        if (YDWEBSERVICEIMPLSERVICE_EXCEPTION != null) {
//            throw YDWEBSERVICEIMPLSERVICE_EXCEPTION;
//        }
//        return YDWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
//    }
//}
