//
//package com.adtech.rts.service;
//
//import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
//import javax.jws.WebService;
//import javax.jws.soap.SOAPBinding;
//import javax.xml.ws.Action;
//
//
///**
// * This class was generated by the JAX-WS RI.
// * JAX-WS RI 2.2.9-b130926.1035
// * Generated source version: 2.2
// */
//@WebService(name = "YdWebServiceImpl", targetNamespace = "http://impl.yd.publish.webservice.fastwork.th.com/")
//@SOAPBinding(style = SOAPBinding.Style.RPC)
//public interface YdWebServiceImpl {
//
//    /**
//     * @param arg0
//     * @return returns java.lang.String
//     */
//    @WebMethod
//    @WebResult(partName = "return")
//    @Action(input = "http://impl.yd.publish.webservice.fastwork.th.com/YdWebServiceImpl/getPersonRequest", output = "http://impl.yd.publish.webservice.fastwork.th.com/YdWebServiceImpl/getPersonResponse")
//    String getPerson(@WebParam(name = "arg0", partName = "arg0") String arg0);
//
//    /**
//     * @param arg0
//     * @return returns java.lang.String
//     */
//    @WebMethod
//    @WebResult(partName = "return")
//    @Action(input = "http://impl.yd.publish.webservice.fastwork.th.com/YdWebServiceImpl/getHjjtCyRequest", output = "http://impl.yd.publish.webservice.fastwork.th.com/YdWebServiceImpl/getHjjtCyResponse")
//    String getHjjtCy(@WebParam(name = "arg0", partName = "arg0") String arg0);
//
//    /**
//     * @param arg0
//     * @return returns java.lang.String
//     */
//    @WebMethod
//    @WebResult(partName = "return")
//    @Action(input = "http://impl.yd.publish.webservice.fastwork.th.com/YdWebServiceImpl/getXyjtCyRequest", output = "http://impl.yd.publish.webservice.fastwork.th.com/YdWebServiceImpl/getXyjtCyResponse")
//    String getXyjtCy(@WebParam(name = "arg0", partName = "arg0") String arg0);
//
//    /**
//     * @param arg0
//     * @return returns java.lang.String
//     */
//    @WebMethod
//    @WebResult(partName = "return")
//    @Action(input = "http://impl.yd.publish.webservice.fastwork.th.com/YdWebServiceImpl/getJzjtCyRequest", output = "http://impl.yd.publish.webservice.fastwork.th.com/YdWebServiceImpl/getJzjtCyResponse")
//    String getJzjtCy(@WebParam(name = "arg0", partName = "arg0") String arg0);
//}
